### PR TITLE
Timers

### PR DESCRIPTION
**Pull request by mineus64**
# Overview

This commit contains all that is needed for the basic framework for a new timer system to replace our scattershot individual timers as well as our Coroutines. Once this is approved and merged, we can start replacing the previous with these new Timers.

This pull partially resolves Issue #6, as it handles the creation of the Timers but not their implementation in general code.

# Timers

The Timer class is a single instance of a timer, which stores data regarding the time remaining in the Timer, an Action to be invoked, etc. etc. It also performs its own tick action (called externally) and handles its own finishing. The Timer is constructed with a method to be invoked when the Timer is up, as well as an ID for the timer, a start time, and an optional boolean controlling whether or not the Timer should be deleted when it is finished.

# TimerController

The TimerController is a singleton class which handles all of the Timers in the game. It includes two Lists of Timers, one for Timers ticking on Update ticks and one for Timers ticking on FixedUpdate ticks. It also includes both methods to add timers specifically to one or the other as well as a generic method to add a timer to either depending on a given boolean. It also invokes the Timer.Tick() method as appropriate.

### CODE REVIEW

**Comment by Spaceguy5234** [comment]
Rejecting this pull request due to performance issues. Primarily with having timers run on an update loop not running concurrently, only iteratively. Instead we have decided to take this existing idea and base it on coroutines for performance, and for the timing to be asynchronous.

**Comment by mineus64** [comment]
OPENED AGAIN, BITCH, I FIXED IT

**Comment by mineus64** [comment]
YOU CAN SLEEP WHEN YOU'RE DEAAAAAAAAAAD

**Comment by Spaceguy5234** [comment]
Great overall, with the ability to expand if needed. Approved.

**Pull request merged**
